In [12]:
import numpy as np
print (np.iinfo(np.int16))

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



# 10.6

In [ ]:
import numpy as np

def get_chess(a):
    arr = np.zeros((a,a))
    
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr
get_chess(5)
# array([[0.]])
#get_chess(4)

# 10.7

In [ ]:
import numpy as np
def shuffle_seed(array):
   seed = np.random.randint(2**32)
   np.random.seed(seed)
   result = np.random.permutation(array)
   return result, seed

# 10.8 


In [14]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

import numpy as np
def min_max_dist(*vectors):
   dists = list()
   for i in range(len(vectors)):
       for j in range(i+1, len(vectors)):
           dists.append(np.linalg.norm(vectors[i] - vectors[j]))
   return min(dists), max(dists)

min_max_dist(vec1,vec2,vec3)

(5.196152422706632, 10.392304845413264)

# 10.9

In [20]:
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

import numpy as np
def any_normal(*vectors):
   for i in range(len(vectors)):
       for j in range(i+1, len(vectors)):
           if np.dot(vectors[i], vectors[j]) == 0:
               return True
   return False

any_normal(vec1,vec2,vec3)



True

# 10.10

In [23]:

import numpy as np
def get_loto(num):
   loto = np.random.randint(1,101, size=(num,  5, 5))
   return loto

get_loto(3)

array([[[ 93,  40,  73,  48,  63],
        [ 90,  60,  20,   2,  63],
        [ 42,  64,  37,  13,  58],
        [ 60,  29,  43,  62,  99],
        [ 66,  63,  97,  37,  15]],

       [[ 71,  91,  28,  69,  22],
        [ 56,  58,   5,   5,  40],
        [ 26,  67,  39,  88,  30],
        [ 63,  90,  89,  49,  99],
        [ 87,  45,  23,  81,   6]],

       [[ 73,  46,  34,  67,  89],
        [ 88, 100,  73,  82,  28],
        [ 47,  42,  57,  94,  94],
        [ 50,  52,  75,  16,  53],
        [  1,  93,  67,  66,  22]]])

# 10.11

In [25]:
import numpy as np
def get_unique_loto(num):
   sample = np.arange(1, 101)
   res = list()
   for i in range(num):
       res.append(np.random.choice(sample,
           replace=False, size=(5, 5)))
   res = np.array(res)
   return res

get_unique_loto(3)

array([[[ 15,  77,  94,  20,  54],
        [ 34,  89,  67,  42,  56],
        [ 97,  59,  64,  96,  74],
        [ 79,  92,  33,  69,   7],
        [ 62,  55,  49,   1,  93]],

       [[ 78,  62,   3,  83,  37],
        [ 50,  91,  89,  88, 100],
        [ 79,  13,  18,  70,  72],
        [ 25,  61,  38,  22,  56],
        [ 46,  94,  11,  75,  99]],

       [[ 98,  18,  49,  94,  48],
        [ 44,  10,  67,  61,  89],
        [ 86,   3,  82,  70,  93],
        [ 88,   6,  21,  57,   9],
        [ 15,  19,  58,  69,  12]]])