In [1]:
import numpy as np

In [2]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [3]:
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2

[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [4]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2
# array([24. , 24. , 25.2, 32.5])

array([24. , 24. , 25.2, 32.5])

In [5]:
vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

array([ 0,  1,  4,  9, 16], dtype=int32)

In [6]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2
# array([False, False,  True, False])

array([False, False,  True, False])

In [7]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

array([ True,  True,  True,  True, False,  True, False])

# Продвинутые операции с векторами

In [9]:
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


In [10]:
length = np.linalg.norm(vec)
print(length)

5.0


## По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.

In [11]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

12.206555615733702

In [12]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

12.206555615733702

In [13]:
#скалярным произведением двух векторов называют сумму произведений их соответствующих координат. Вот формула для скалярного произведения векторов X и Y из n координат:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0

250.0

In [14]:
scalar_product = np.dot(vec1, vec2)
scalar_product
# 250.0

250.0

## Task 8.4

In [18]:
import numpy as np
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])

print (np.linalg.norm(a)+np.linalg.norm(b) == np.linalg.norm(a+b))
print (np.linalg.norm(a)+np.linalg.norm(c) == np.linalg.norm(a+c))
print (np.linalg.norm(c)+np.linalg.norm(b) == np.linalg.norm(c+b))

False
True
False


In [20]:
#8.5
print ( np.sum(a * b))
print (np.sum(a * c))
print ( np.sum(c * b))

34
4828
68


In [22]:
# Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28
vec.mean()
# 10.75

10.75

In [ ]:
#8.7 - 8.10
from hidden import mystery
# Пишите здесь команды, который помогут
# найти ответы на вопросы
import numpy as np
print(mystery.min())
print(mystery.mean())
print(np.median(mystery))
print(np.std(mystery))