In [1]:
import numpy as np

# Генерация float

In [7]:
# Самой «базовой» функцией в нём можно считать функцию rand. По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно)
np.random.rand() *100
np.random.rand(5)
np.random.rand(2, 3)
np.random.rand(2, 3, 4)

array([[[0.45114184, 0.73842344, 0.18423904, 0.92043598],
        [0.07883308, 0.1874362 , 0.83005093, 0.24034169],
        [0.86142086, 0.58712359, 0.15081277, 0.34544473]],

       [[0.01854328, 0.19761934, 0.16628791, 0.52543512],
        [0.77975922, 0.45281285, 0.05252232, 0.35382071],
        [0.2243229 , 0.58092327, 0.51527213, 0.65264874]]])

In [9]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.85592057, 0.12088289, 0.45483535, 0.66928455],
       [0.10961809, 0.59772723, 0.84290217, 0.41410219],
       [0.95503256, 0.44763826, 0.86398496, 0.57636008]])

In [10]:
# в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:
shape = (2, 3)
np.random.sample(shape)

array([[0.83874462, 0.63524226, 0.67520952],
       [0.9969974 , 0.31045138, 0.05147825]])

In [18]:
# функция uniform:
# uniform(low=0.0, high=1.0, size=None)
np.random.uniform()
# Зададим границы диапазона от -30 до 50:
np.random.uniform(-30, 50)
# Получим пять чисел в интервале от 0.5 до 0.75:
np.random.uniform(0.5, 0.75, size=5)
# Получим массив из двух строк и трёх столбцов из чисел в интервале от -1000 до 500:
np.random.uniform(-1000, 500, size=(2, 3))


array([[-681.18104381,   86.20226367, -748.92612672],
       [-282.48610845, -626.57468077, -443.51250349]])

# Генерация int

In [19]:
# Для генерации целых чисел используется функция random.randint:
# randint(low, high=None, size=None, dtype=int)
np.random.randint(6, 12, size=(3,3))


array([[ 6, 10,  9],
       [11,  6,  8],
       [ 9, 11,  8]])

# Генерация выборок

In [20]:
# Просто перемешать все числа в массиве позволяет функция random.shuffle.
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr
# array([0, 5, 1, 3, 2, 4])

[0 1 2 3 4 5]
None


array([3, 4, 5, 1, 0, 2])

In [21]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['ACDC' 'Pink Floyd' 'Deep Purple' 'The Beatles']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [22]:
# Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)

array([2, 8, 4, 9, 0, 3, 1, 7, 5, 6])

In [25]:
# Чтобы получить случайный набор объектов из массива, используется функция random.choice:
# choice(a, size=None, replace=True)
#
#        a — массив или число для генерации arange(a);
#        size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
#        replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).

workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
 
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['Nikita' 'John']


# Seed генератора псевдослучайных чисел

In [28]:
# Самостоятельно задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295)
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [30]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]
